### ISSUE TITLE
Align system information to center

### ISSUE THREAD

**Issue by gurglingtonic** [Siddy212/canvas-es#3]
Hi there! Appreciate you sharing this theme. I've noticed a minor flaw.

It will be great to center-align the system information. I'm using RG35XXH.

The photos indicate "1859 GAMES" and "12 COLLECTIONS" are off-center.

![IMG_7691](https://github.com/Siddy212/canvas-es/assets/3590384/728ba70b-91f3-4f51-8587-06f644889b4b)
![IMG_7692](https://github.com/Siddy212/canvas-es/assets/3590384/78de7ece-a175-452a-8422-2323873fc94e)

**Comment by Siddy212** [comment]
Hey, thanks for catching this! I'll look into centering the icon and numbers below. It's tricky with the logo to make it look clean.
